export const INGREDIENTS_REQUEST: 'INGREDIENTS_REQUEST' = 'INGREDIENTS_REQUEST';
export const INGREDIENTS_SUCCESS: 'INGREDIENTS_SUCCESS' = 'INGREDIENTS_SUCCESS';
export const INGREDIENTS_FAILED: 'INGREDIENTS_FAILED' = 'INGREDIENTS_FAILED';

export const CONSTRUCTOR_SORT_INGREDIENT: 'CONSTRUCTOR_SORT_INGREDIENT' = 'CONSTRUCTOR_SORT_INGREDIENT';
export const CONSTRUCTOR_ADD_INGREDIENT: 'CONSTRUCTOR_ADD_INGREDIENT' = 'CONSTRUCTOR_ADD_INGREDIENT';
export const CONSTRUCTOR_REMOVE_INGREDIENT: 'CONSTRUCTOR_REMOVE_INGREDIENT' = 'CONSTRUCTOR_REMOVE_INGREDIENT';
export const CONSTRUCTOR_ADD_BUN: 'CONSTRUCTOR_ADD_BUN' = 'CONSTRUCTOR_ADD_BUN';
export const CONSTRUCTOR_CLEAN: 'CONSTRUCTOR_CLEAN' = 'CONSTRUCTOR_CLEAN';

export const CONSTRUCTOR_UPDATE_SUM: 'CONSTRUCTOR_UPDATE_SUM' = 'CONSTRUCTOR_UPDATE_SUM';

export const ORDER_REQUEST: 'ORDER_REQUEST' = 'ORDER_REQUEST';
export const ORDER_SUCCESS: 'ORDER_SUCCESS' = 'ORDER_SUCCESS';
export const ORDER_ERROR: 'ORDER_ERROR' = 'ORDER_ERROR';

export const REGISTER_SUBMIT: 'REGISTER_SUBMIT' = 'REGISTER_SUBMIT';
export const REGISTER_SUCCESS: 'REGISTER_SUCCESS' = 'REGISTER_SUCCESS';
export const REGISTER_ERROR: 'REGISTER_ERROR' = 'REGISTER_ERROR';

export const LOGIN_SUBMIT: 'LOGIN_SUBMIT' = 'LOGIN_SUBMIT';
export const LOGIN_SUCCESS: 'LOGIN_SUCCESS' = 'LOGIN_SUCCESS';
export const LOGIN_ERROR: 'LOGIN_ERROR' = 'LOGIN_ERROR';

export const EDIT_PROFILE_SUBMIT: 'EDIT_PROFILE_SUBMIT' = 'EDIT_PROFILE_SUBMIT';
export const EDIT_PROFILE_SUCCESS: 'EDIT_PROFILE_SUCCESS' = 'EDIT_PROFILE_SUCCESS';
export const EDIT_PROFILE_ERROR: 'EDIT_PROFILE_ERROR' = 'EDIT_PROFILE_ERROR';

export const GET_USER_REQUEST: 'GET_USER_REQUEST' = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS: 'GET_USER_SUCCESS' = 'GET_USER_SUCCESS';
export const GET_USER_ERROR: 'GET_USER_ERROR' = 'GET_USER_ERROR';

export const REFRESH_TOKEN_REQUEST: 'REFRESH_TOKEN_REQUEST' = 'REFRESH_TOKEN_REQUEST';
export const REFRESH_TOKEN_SUCCESS: 'REFRESH_TOKEN_SUCCESS' = 'REFRESH_TOKEN_SUCCESS';
export const REFRESH_TOKEN_ERROR: 'REFRESH_TOKEN_ERROR' = 'REFRESH_TOKEN_ERROR';

export const LOGOUT_REQUEST: 'LOGOUT_REQUEST' = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS: 'LOGOUT_SUCCESS' = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR: 'LOGOUT_ERROR' = 'LOGOUT_ERROR';

export const FORGOT_PASSWORD_SUBMIT: 'FORGOT_PASSWORD_SUBMIT' = 'FORGOT_PASSWORD_SUBMIT';
export const FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS' = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_ERROR: 'FORGOT_PASSWORD_ERROR' = 'FORGOT_PASSWORD_ERROR';

export const RESET_PASSWORD_SUBMIT: 'RESET_PASSWORD_SUBMIT' = 'RESET_PASSWORD_SUBMIT';
export const RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS' = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_ERROR: 'RESET_PASSWORD_ERROR' = 'RESET_PASSWORD_ERROR';

export const SELECT_INGREDIENT: 'SELECT_INGREDIENT' = 'SELECT_INGREDIENT';
export const UNSELECT_INGREDIENT: 'UNSELECT_INGREDIENT' = 'UNSELECT_INGREDIENT';
