export const INGREDIENTS_REQUEST = 'INGREDIENTS_REQUEST';
export const INGREDIENTS_SUCCESS = 'INGREDIENTS_SUCCESS';
export const INGREDIENTS_FAILED = 'INGREDIENTS_FAILED';

export const CONSTRUCTOR_SORT_INGREDIENT = 'CONSTRUCTOR_SORT_INGREDIENT';
export const CONSTRUCTOR_ADD_INGREDIENT = 'CONSTRUCTOR_ADD_INGREDIENT';
export const CONSTRUCTOR_REMOVE_INGREDIENT = 'CONSTRUCTOR_REMOVE_INGREDIENT';
export const CONSTRUCTOR_ADD_BUN = 'CONSTRUCTOR_ADD_BUN';
export const CONSTRUCTOR_CLEAN = 'CONSTRUCTOR_CLEAN';

export const CONSTRUCTOR_UPDATE_SUM = 'CONSTRUCTOR_UPDATE_SUM';

export const INGREDIENTS_DETAILS = 'INGREDIENTS_DETAILS';

export const ORDER_REQUEST = 'ORDER_REQUEST';
export const ORDER_SUCCESS = 'ORDER_SUCCESS';
export const ORDER_ERROR = 'ORDER_ERROR';
